export const STATIC_FILTERS = {
  makes: [
    "Adam",
    "Audi",
    "BAIC",
    "BMW",
    "BYD",
    "Buick",
    "Cadillac",
    "Changan",
    "Chery",
    "Chevrolet",
    "DFSK",
    "Daehan",
    "Daewoo",
    "Daihatsu",
    "Datsun",
    "Deepal",
    "Dongfeng",
    "FAW",
    "Ford",
    "GMC",
    "Haval",
    "Hino",
    "Honda",
    "Hyundai",
    "Isuzu",
    "JAC",
    "JMC",
    "JW",
    "Jaguar",
    "Jeep",
    "Jetour",
    "KIA",
    "Land",
    "Lexus",
    "MG",
    "MINI",
    "Mazda",
    "Mercedes",
    "Mitsubishi",
    "Nissan",
    "ORA",
    "Peugeot",
    "Porsche",
    "Prince",
    "Proton",
    "Range",
    "Seres",
    "Sogo",
    "Subaru",
    "Suzuki",
    "Tesla",
    "Toyota",
    "United",
    "Volkswagen",
  ],
  transmissions: ["Automatic", "Manual"],
  fuel_types: ["CNG", "Diesel", "Electric", "Hybrid", "Petrol"],
  seller_types: ["Featured", "Individual"],
  year_range: { min: 1965, max: 2025 },
  price_range: { min: 150000, max: 171000000 },
  mileage_range: { min: 1, max: 1000000 },
}

export type StaticFilters = typeof STATIC_FILTERS
